name       : haskell-monad-loops
version    : 0.4.3
release    : 3
source     :
    - http://hackage.haskell.org/package/monad-loops-0.4.3/monad-loops-0.4.3.tar.gz : 7eaaaf6bc43661e9e86e310ff8c56fbea16eb6bf13c31a2e28103138ac164c18
license    : BSD-3-Clause
component  : programming.haskell
summary    : Some useful control operators for looping.
description: |
    Some useful control operators for looping.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
